/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;


import javax.swing.JOptionPane;


/**
 *
 * @author Manuela Gomez
 */
public class VentanaInicio extends javax.swing.JFrame  {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        btnIniciarPartida = new javax.swing.JButton();
        lblNumeroFilas = new javax.swing.JLabel();
        lblNumeroColumnas = new javax.swing.JLabel();
        txtNumeroFilas = new javax.swing.JTextField();
        txtNumeroColumnas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInicio.setBackground(new java.awt.Color(0, 0, 0));

        btnIniciarPartida.setBackground(new java.awt.Color(255, 255, 255));
        btnIniciarPartida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarPartida.setForeground(new java.awt.Color(0, 153, 0));
        btnIniciarPartida.setText("INICIAR PARTIDA");
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });

        lblNumeroFilas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroFilas.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroFilas.setText("N° filas:");

        lblNumeroColumnas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNumeroColumnas.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroColumnas.setText("N° Columnas:");

        txtNumeroFilas.setBackground(new java.awt.Color(255, 255, 255));

        txtNumeroColumnas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btnIniciarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroFilas)
                            .addComponent(lblNumeroColumnas))
                        .addGap(97, 97, 97)
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumeroFilas)
                    .addComponent(txtNumeroFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroColumnas)
                    .addComponent(txtNumeroColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnIniciarPartida)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        // TODO add your handling code here:
        int filas = Integer.parseInt(txtNumeroFilas.getText());
        int columnas = Integer.parseInt(txtNumeroColumnas.getText());
       

        if (Integer.parseInt(txtNumeroFilas.getText()) >= 31 || Integer.parseInt(txtNumeroColumnas.getText()) >= 31) {
            JOptionPane.showMessageDialog(null, "Ingreso demasiadas filas y columnas, minimo 30");
            return;
        
        }
        VentanaJuego ventana = new VentanaJuego(filas, columnas);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JLabel lblNumeroColumnas;
    private javax.swing.JLabel lblNumeroFilas;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JTextField txtNumeroColumnas;
    private javax.swing.JTextField txtNumeroFilas;
    // End of variables declaration//GEN-END:variables

    //public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {
//
//    JButton[][] almacenes;
//    private ControladorAlmacen controladorAlmacen;
//    private ControladorCliente controladorCliente;
//
//    /**
//     * Creates new form Ventana
//     */
//    public VentanaPrincipal() {
//        initComponents();
//        setLocationRelativeTo(this);
//        almacenes = new JButton[3][5];
//        controladorAlmacen = new ControladorAlmacen();
//        controladorCliente = new ControladorCliente();
//        cargarBotones();
//        validarPosiciones();
//        llenarTabla();
//      private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // TODO add your handling code here:
//        if (txtCedula.getText().isEmpty() || txtNombreCompleto.getText().isEmpty()
//                || txtTelefono.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
//            return;
//        }
//        String nombre = txtNombreCompleto.getText();
//        String cedula = txtCedula.getText();
//        String telefono = txtTelefono.getText();
//        Cliente cliente = new Cliente(nombre, cedula, telefono);
//        boolean respuesta = controladorCliente.editarCliente(cliente);
//        if (respuesta) {
//            JOptionPane.showMessageDialog(null, " El cliente ha sido editado");
//            limpiarCampos();
//            llenarTabla();
//        } else {
//            JOptionPane.showMessageDialog(null, "El cliente no pudo ser editado");
//        }
//    }                                         
//
//    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // TODO add your handling code here:
//        if (txtCedula.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Ingrese un numero de cedula para buscar un cliente");
//            return;
//        }
//
//        String cedula = txtCedula.getText();
//        Cliente cliente = controladorCliente.buscarCliente(cedula);
//        if (cliente != null) {
//            txtNombreCompleto.setText(cliente.getNombreCompleto());
//            txtCedula.setText(cliente.getCedula());
//            txtTelefono.setText(cliente.getTelefono());
//
//        } else {
//            JOptionPane.showMessageDialog(null, "No se encontró un cliente con cédula " + cedula);
//        }
//    }                                         
//
//    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        // TODO add your handling code here:
//        if (txtCedula.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Ingrese un número de cédula para eliminar un cliente");
//            return;
//        }
//        String cedula = txtCedula.getText();
//        boolean respuesta = controladorCliente.eliminarCliente(cedula);
//        if (respuesta) {
//            JOptionPane.showMessageDialog(null, "El cliente ha sido eliminado");
//            limpiarCampos();
//            llenarTabla();
//        } else {
//            JOptionPane.showMessageDialog(null, "El cliente no se pudo eliminar");
//        }
//    }                                           
//
//    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {                                             
//        String cedula = txtCedula.getText();
//        String telefono = txtTelefono.getText();
//        String nombre = txtNombreCompleto.getText();
//        Cliente cliente = new Cliente(nombre, cedula, telefono);
//
//        if (controladorCliente.registrarCliente(cliente)) {
//            JOptionPane.showMessageDialog(null, "Cliente registrado");
//            llenarTabla();
//            limpiarCampos();
//        } else {
//            JOptionPane.showMessageDialog(null, "El cliente ya esta registrado");
//        }
//    }                                            
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaPrincipal().setVisible(true);
//            }
//        });
//    }
//METODO CARGAR BOTONES
//
//
//    private void validarPosiciones() {
//        for (int i = 0; i < almacenes.length; i++) {
//            for (int j = 0; j < almacenes[i].length; j++) {
//                Almacen almacen = controladorAlmacen.obtenerAlmacen(i, j);
//                if (almacen.getEstado().equals(Almacen.DISPONIBLE)) {
//                    almacenes[i][j].setBackground(Color.WHITE);
//                } else if (almacen.getEstado().equals(Almacen.OCUPADO)) {
//                    almacenes[i][j].setBackground(Color.BLUE);
//                } else if (almacen.getEstado().equals(Almacen.DESHABILITADO)) {
//                    almacenes[i][j].setBackground(Color.GRAY);
//                }
//            }
//        }
//
//    }
//
//    @Override
//    public void actionPerformed(ActionEvent ae) {
//        for (int i = 0; i < almacenes.length; i++) {
//            for (int j = 0; j < almacenes[i].length; j++) {
//                if (ae.getSource().equals(almacenes[i][j])) {
//                    Almacen almacen = controladorAlmacen.obtenerAlmacen(i, j);
//                    if (almacen.getEstado().equals(Almacen.DISPONIBLE)) {
//                        VentanaAsignacion ventana = new VentanaAsignacion(almacen);
//                        ventana.setVisible(true);
//                        this.dispose();
//                    } else if (almacen.getEstado().equals(Almacen.OCUPADO)) {
//                        VentanaVerificacion ventana = new VentanaVerificacion(almacen);
//                        ventana.setVisible(true);
//                        this.dispose();
//                    } else if (almacen.getEstado().equals(Almacen.DESHABILITADO)) {
//                        VentanaMotivo ventana = new VentanaMotivo(almacen);
//                        ventana.setVisible(true);
//                        this.dispose();
//                    }
//
//                }
//            }
//        }
//    }
//
//    private void llenarTabla() {
//        DefaultTableModel modelo = new DefaultTableModel();
//        LSE<Cliente> clientes = controladorCliente.getClientes();
//
//        modelo.setColumnIdentifiers(new Object[]{"Nombre", "Cédula", "Telefono"});
//        tablaClientes.setModel(modelo);
//        for (int i = 0; i < clientes.size(); i++) {
//            modelo.addRow(new Object[]{
//                clientes.get(i).getNombreCompleto(),
//                clientes.get(i).getCedula(),
//                clientes.get(i).getTelefono()
//            });
//
//        }
//
//    }
//
//    private void limpiarCampos() {
//        txtNombreCompleto.setText("");
//        txtCedula.setText("");
//        txtTelefono.setText("");
//    }   
    //METODO REGRESAR
//    //  private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        // TODO add your handling code here:
//        VentanaPrincipal ventana = new VentanaPrincipal();
//        ventana.setVisible(true);
//        this.dispose();
   // ----------------------------
//    public class VentanaProductos extends javax.swing.JFrame {
//
//    private ControladorProducto controlador;
//    private Almacen almacen;
//    
//    /**
//     * Creates new form VentanaProductos
//     */
//    public VentanaProductos(Almacen almacen) {
//        initComponents();
//        setLocationRelativeTo(this);
//        this.almacen = almacen;
//        controlador = new ControladorProducto(almacen);
//        llenarTabla();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        lblProducto = new javax.swing.JLabel();
//        lblNombreProducto = new javax.swing.JLabel();
//        lblCodigoProducto = new javax.swing.JLabel();
//        txtNombre = new javax.swing.JTextField();
//        txtCodigo = new javax.swing.JTextField();
//        btnRegistrar = new javax.swing.JButton();
//        btnDesocuparAlmacen = new javax.swing.JButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        tablaProductos = new javax.swing.JTable();
//        btnEditar = new javax.swing.JButton();
//        btnBuscar = new javax.swing.JButton();
//        btnEliminarProducto = new javax.swing.JButton();
//        btnEliminarInventario = new javax.swing.JButton();
//        btnRegresar = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
//
//        lblProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
//        lblProducto.setText("Producto");
//
//        lblNombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        lblNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
//        lblNombreProducto.setText("Nombre del producto:");
//
//        lblCodigoProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        lblCodigoProducto.setForeground(new java.awt.Color(255, 255, 255));
//        lblCodigoProducto.setText("Código del producto:");
//
//        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
//        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnRegistrar.setForeground(new java.awt.Color(0, 102, 51));
//        btnRegistrar.setText("REGISTRAR");
//        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnRegistrarActionPerformed(evt);
//            }
//        });
//
//        btnDesocuparAlmacen.setBackground(new java.awt.Color(255, 255, 255));
//        btnDesocuparAlmacen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnDesocuparAlmacen.setForeground(new java.awt.Color(0, 102, 51));
//        btnDesocuparAlmacen.setText("DESOCUPAR ALMACEN");
//        btnDesocuparAlmacen.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnDesocuparAlmacenActionPerformed(evt);
//            }
//        });
//
//        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
//            },
//            new String [] {
//                "Title 1", "Title 2", "Title 3", "Title 4"
//            }
//        ));
//        jScrollPane1.setViewportView(tablaProductos);
//
//        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
//        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnEditar.setForeground(new java.awt.Color(0, 102, 51));
//        btnEditar.setText("EDITAR");
//        btnEditar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnEditarActionPerformed(evt);
//            }
//        });
//
//        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
//        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnBuscar.setForeground(new java.awt.Color(0, 102, 51));
//        btnBuscar.setText("BUSCAR");
//        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnBuscarActionPerformed(evt);
//            }
//        });
//
//        btnEliminarProducto.setBackground(new java.awt.Color(255, 255, 255));
//        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnEliminarProducto.setForeground(new java.awt.Color(0, 102, 51));
//        btnEliminarProducto.setText("ELIMINAR PRODUCTO");
//        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnEliminarProductoActionPerformed(evt);
//            }
//        });
//
//        btnEliminarInventario.setBackground(new java.awt.Color(255, 255, 255));
//        btnEliminarInventario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnEliminarInventario.setForeground(new java.awt.Color(0, 102, 51));
//        btnEliminarInventario.setText("ELIMINAR INVENTARIO");
//        btnEliminarInventario.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnEliminarInventarioActionPerformed(evt);
//            }
//        });
//
//        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
//        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        btnRegresar.setForeground(new java.awt.Color(0, 102, 51));
//        btnRegresar.setText("REGRESAR");
//        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnRegresarActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(jPanel1Layout.createSequentialGroup()
//                        .addGap(43, 43, 43)
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                .addComponent(lblCodigoProducto)
//                                .addComponent(lblNombreProducto)
//                                .addComponent(txtNombre)
//                                .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
//                            .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                        .addGap(0, 1, Short.MAX_VALUE))
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                        .addGap(0, 0, Short.MAX_VALUE)
//                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addComponent(btnDesocuparAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(btnEliminarInventario)))))
//                .addGap(18, 18, 18)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addGap(104, 104, 104)
//                .addComponent(lblProducto)
//                .addGap(97, 97, 97)
//                .addComponent(btnRegresar)
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addContainerGap(80, Short.MAX_VALUE)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(69, 69, 69))
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                .addGap(34, 34, 34)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(lblProducto)
//                    .addComponent(btnRegresar))
//                .addGap(32, 32, 32)
//                .addComponent(lblNombreProducto)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(47, 47, 47)
//                .addComponent(lblCodigoProducto)
//                .addGap(26, 26, 26)
//                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnRegistrar)
//                    .addComponent(btnBuscar))
//                .addGap(34, 34, 34)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnEliminarInventario)
//                    .addComponent(btnEditar))
//                .addGap(74, 74, 74)
//                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnDesocuparAlmacen)
//                    .addComponent(btnEliminarProducto))
//                .addGap(68, 68, 68))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
//
//        pack();
//    }// </editor-fold>                        
//
//    private void btnDesocuparAlmacenActionPerformed(java.awt.event.ActionEvent evt) {                                                    
//        // TODO add your handling code here:
//        if(almacen.getProductos().size() == 0){
//            controlador.desocuparAlmacen();
//            JOptionPane.showMessageDialog(null, "Almacen desocupado exitosamente");
//            VentanaPrincipal ventana = new VentanaPrincipal();
//            ventana.setVisible(true);
//            this.dispose();  
//        }else{
//            JOptionPane.showMessageDialog(null, "Primero debe eliminar todos los productos");
//        }
//    }                                                   
//
//    private void btnEliminarInventarioActionPerformed(java.awt.event.ActionEvent evt) {                                                      
//        // TODO add your handling code here:
//        controlador.eliminarInventario();
//        JOptionPane.showMessageDialog(null,"Bodega sin productos");
//        llenarTabla();
//    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        String cedula = txtCedula.getText();
//        String usuario = txtUsuario.getText();
//        String contrasenia = txtContrasenia.getText();
//
//        Cliente cliente = controlador.buscarCliente(cedula);
//        if (cliente != null) {
//            controlador.ocuparAlmacen(almacen, cliente, usuario, contrasenia);
//            JOptionPane.showMessageDialog(null, "Almacen asignado");
//            VentanaPrincipal ventana = new VentanaPrincipal();
//            ventana.setVisible(true);
//            this.dispose();
//        }
//
//    }                                          
//
//    private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {                                                
//        // TODO add your handling code here:
//        String motivo = JOptionPane.showInputDialog("Motivo de deshabilitación:");
//        
//        if(!motivo.isEmpty()){
//            controlador.deshabilitarAlmacen(almacen, motivo);
//            JOptionPane.showMessageDialog(null, "Deshabilitado correctamente");
//            VentanaPrincipal ventana = new VentanaPrincipal();
//            ventana.setVisible(true);
//            this.dispose();
//        }else{
//            JOptionPane.showMessageDialog(null, "Ingrese un motivo");
//        }
//    public final class Singleton {
//
//    private static Singleton INSTANCIA = new Singleton();
//
//    private LSE<Cliente> clientes;
//    private Almacen[][] almacenes;
//
//    private Singleton() {
//        clientes = leerCliente();
//        almacenes = leerAlmacen();
//
//    }
//
//    public static Singleton getINSTANCIA() {
//        return INSTANCIA;
//    }
//
//    public LSE<Cliente> getClientes() {
//        return clientes;
//    }
//
//    public Almacen[][] getAlmacenes() {
//        return almacenes;
//    }
//
//    public void escribirCliente() {
//        try {
//            FileOutputStream archivo = new FileOutputStream("clientes.dat");
//            ObjectOutputStream escritor = new ObjectOutputStream(archivo);
//            escritor.writeObject(clientes);
//        } catch (IOException ex) {
//            ex.printStackTrace();
//        }
//    }
    //
//    public Almacen[][] leerAlmacen() {
//        try {
//            FileInputStream archivo = new FileInputStream("almacenes.dat");
//            ObjectInputStream lector = new ObjectInputStream(archivo);
//            return (Almacen[][]) lector.readObject();
//        } catch (IOException | ClassNotFoundException ex) {
//            ex.printStackTrace();
//            return new Almacen[3][5];
//    ---------COMO CARGAR SIN PONER EN EL MAIN
//    ME DIRIGO AL CONTROLADOR DEL ALMACEN EN EL INIT
//    private void initAlmacenes() {
//        if(almacenes[0][0] == null){
//        for (int i = 0; i < almacenes.length; i++) {
//            for (int j = 0; j < almacenes[i].length; j++) {
//                almacenes[i][j] = new Almacen();
//            }
//        }
//                Singleton.getINSTANCIA().escribirAlmacen();
//            }else{
//            Singleton.getINSTANCIA().leerAlmacen();
//        }
//    }
}
